# Replace the text below to customize your site
site_name: Edgardo Saracho - UTEC & Fab Lab Barcelona
site_description: ESPECIALIZACIÓN EN FABRICACIÓN DIGITAL E INNOVACIÓN
site_author: Edgardo Saracho - UTEC & Fab Lab Barcelona
copyright: Copyleft 2024 "Edgardo_Saracho" - GNU Free Documentation License
repo_name: 'Name : Edgardo_Saracho'
site_url: https://edg-saracho.github.io/Edgardo_Saracho/
repo_url: https://github.com/EDG-Saracho/Edgardo_Saracho.git


nav:
  - Inicio: index.md
  - Sobre mí: about/me.md
  - Modulos Técnicos :
    - MT01: tecnicos/mt01.md
    - MT02: tecnicos/mt02.md
    - MT03: tecnicos/mt03.md
    - FP01: tecnicos/fp01.md
    - MT04: tecnicos/mt04.md
    - MT05: tecnicos/mt05.md
  - Modulos Diseño :
    - MD01: diseno/md01.md
    - MD02: diseno/md02.md
  - Modulos Innovación :
    - MI01: innovacion/mi01.md
  - Proyecto Integrador:
    - Ideas Iniciales: proyecto/proyecto.md


extra:
  social:
    # For other social icons at https://squidfunk.github.io/mkdocs-material/setup/adding-social-links/
    - icon: fontawesome/brands/medium
      link: https://medium.com/
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/edg.design.uy/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/
    - icon: fontawesome/brands/linkedin
      link: "https://www.linkedin.com/in/edg-uy/"
    - icon: fontawesome/brands/github
      link: "https://github.com/"

theme:
  name: material
  palette:
    # try other colors https://squidfunk.github.io/mkdocs-material/getting-started/#primary-colors
    primary: custom
    accent: teal
  font:
    # See available fonts at https://fonts.google.com/
    text: Poppins
    code: Cutive Mono
  logo: images/Edg_iso_blanco.png
  favicon: images/Edg_iso.svg
  features:
    - instant
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    # - navigation.prune
    # - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking

plugins:
  - search
  - git-revision-date-localized:
      fallback_to_build_date: true

markdown_extensions:
  - extra
  - smarty
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

  - md_in_html
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      base_path: 'docs'
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - attr_list
  - pymdownx.tabbed


extra_css:
  - stylesheets/extra.css
  - https://unpkg.com/material-components-web@latest/dist/material-components-web.min.css
